import { Resend } from "resend";

export interface ContactLead {
  name: string;
  school: string;
  email: string;
  phone: string;
  students: string;
  message: string;
  campaign: string;
  timestamp: string;
}

const DEFAULT_FROM = "Melo <hey@jstarstudios.com>";
const DEFAULT_TO = "melo@jstarstudios.com";

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function emailShell(args: {
  preview: string;
  eyebrow: string;
  title: string;
  body: string;
  content: string;
  footer: string;
}) {
  return `<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>${escapeHtml(args.title)}</title>
  </head>
  <body style="margin:0;background:#f5f1e8;color:#29251f;font-family:Arial,Helvetica,sans-serif;">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;">${escapeHtml(args.preview)}</div>
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f5f1e8;padding:32px 12px;">
      <tr>
        <td align="center">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;border:1px solid #ded6c8;border-radius:18px;overflow:hidden;background:#fffdf8;box-shadow:0 12px 40px rgba(73,58,33,.08);">
            <tr>
              <td style="padding:20px 26px;background:#29251f;color:#fffdf8;">
                <span style="font-family:Georgia,serif;font-size:25px;font-weight:700;letter-spacing:-.4px;">Melo</span>
                <span style="float:right;padding-top:8px;color:#d8b15c;font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;">School management, simplified.</span>
              </td>
            </tr>
            <tr>
              <td style="padding:36px 28px 30px;">
                <p style="margin:0 0 10px;color:#b07b18;font-size:11px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase;">${escapeHtml(args.eyebrow)}</p>
                <h1 style="margin:0 0 16px;color:#29251f;font-family:Georgia,serif;font-size:32px;line-height:1.15;font-weight:700;">${escapeHtml(args.title)}</h1>
                <p style="margin:0 0 26px;color:#675f54;font-size:15px;line-height:1.7;">${escapeHtml(args.body)}</p>
                ${args.content}
              </td>
            </tr>
            <tr>
              <td style="padding:20px 28px;border-top:1px solid #ebe4d8;color:#82796d;font-size:12px;line-height:1.6;">
                ${escapeHtml(args.footer)}<br />Melo by J StaR Studios
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

function detailRow(label: string, value: string) {
  return `<tr>
    <td style="width:120px;padding:11px 12px;border-bottom:1px solid #eee7dc;color:#82796d;font-size:12px;font-weight:700;text-transform:uppercase;vertical-align:top;">${escapeHtml(label)}</td>
    <td style="padding:11px 12px;border-bottom:1px solid #eee7dc;color:#29251f;font-size:14px;line-height:1.5;word-break:break-word;">${escapeHtml(value)}</td>
  </tr>`;
}

function internalHtml(lead: ContactLead) {
  const details = [
    detailRow("Name", lead.name),
    detailRow("School", lead.school),
    detailRow("Email", lead.email),
    detailRow("Phone", lead.phone),
    detailRow("Students", lead.students),
    detailRow("Campaign", lead.campaign),
    detailRow("Submitted", new Date(lead.timestamp).toLocaleString("en-NG", { timeZone: "Africa/Lagos" }) + " WAT"),
    detailRow("Message", lead.message),
  ].join("");

  return emailShell({
    preview: `${lead.name} from ${lead.school} requested a Melo demo.`,
    eyebrow: "New demo enquiry",
    title: `${lead.school} wants to see Melo`,
    body: "A new lead submitted the Melo demo form. Reply to this email to respond directly to them.",
    content: `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #ded6c8;border-radius:12px;overflow:hidden;background:#ffffff;">${details}</table>`,
    footer: "This notification was generated by the Melo website contact form.",
  });
}

function confirmationHtml(lead: ContactLead) {
  return emailShell({
    preview: "We received your Melo demo request.",
    eyebrow: "Request received",
    title: `Thanks for reaching out, ${lead.name}`,
    body: `We received your request for ${lead.school}. The Melo team will review your details and respond within 24 hours.`,
    content: `<div style="padding:20px;border:1px solid #e6dcc9;border-radius:12px;background:#fbf6eb;">
      <p style="margin:0 0 8px;color:#29251f;font-size:14px;font-weight:700;">What happens next?</p>
      <p style="margin:0;color:#675f54;font-size:14px;line-height:1.7;">We’ll contact you to arrange a short walkthrough focused on your school’s academic, billing, and family-management needs.</p>
    </div>`,
    footer: "You received this because your email was used to request a Melo demo. If this was not you, no action is needed.",
  });
}

function internalText(lead: ContactLead) {
  return [
    "New Melo demo enquiry",
    "",
    `Name: ${lead.name}`,
    `School: ${lead.school}`,
    `Email: ${lead.email}`,
    `Phone: ${lead.phone}`,
    `Students: ${lead.students}`,
    `Campaign: ${lead.campaign}`,
    `Submitted: ${lead.timestamp}`,
    `Message: ${lead.message}`,
  ].join("\n");
}

export async function deliverContactLead(lead: ContactLead) {
  const apiKey = process.env.RESEND_API_KEY?.trim();
  if (!apiKey) {
    return { delivered: false as const, reason: "email_not_configured" as const };
  }

  const resend = new Resend(apiKey);
  const from = process.env.MELO_EMAIL_FROM?.trim() || DEFAULT_FROM;
  const to = process.env.MELO_CONTACT_TO?.trim() || DEFAULT_TO;

  try {
    const notification = await resend.emails.send({
      from,
      to,
      replyTo: lead.email,
      subject: `New Melo demo request — ${lead.school}`,
      html: internalHtml(lead),
      text: internalText(lead),
    });

    if (notification.error || !notification.data?.id) {
      console.error("[Contact email] Resend rejected the internal notification", {
        code: notification.error?.name,
        statusCode: notification.error?.statusCode,
      });
      return { delivered: false as const, reason: "provider_error" as const };
    }

    let confirmationSent = false;
    try {
      const confirmation = await resend.emails.send({
        from,
        to: lead.email,
        replyTo: to,
        subject: "We received your Melo demo request",
        html: confirmationHtml(lead),
        text: `Hi ${lead.name},\n\nWe received your Melo demo request for ${lead.school}. The Melo team will respond within 24 hours.\n\nMelo by J StaR Studios`,
      });

      confirmationSent = Boolean(confirmation.data?.id && !confirmation.error);
      if (!confirmationSent) {
        console.error("[Contact email] Internal notification delivered, but confirmation was rejected", {
          code: confirmation.error?.name,
          statusCode: confirmation.error?.statusCode,
        });
      }
    } catch (error) {
      console.error("[Contact email] Internal notification delivered, but confirmation failed", error);
    }

    return {
      delivered: true as const,
      notificationId: notification.data.id,
      confirmationSent,
    };
  } catch (error) {
    console.error("[Contact email] Resend request failed", error);
    return { delivered: false as const, reason: "provider_error" as const };
  }
}
