"use client";
import { useState } from "react";
import { useMutation, useQuery } from "convex/react";
import type { Id } from "../../../../packages/convex/_generated/dataModel";
import type { UsageEntitlement } from "../../../../packages/convex/functions/foundation/usageContract";
const input =
  "block w-full rounded-lg border border-slate-300 bg-white p-2.5 text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-600 font-medium placeholder:text-slate-400";
const formCard =
  "grid gap-3 sm:grid-cols-2 rounded-xl bg-slate-50 border border-slate-200 p-4";
const primaryBtn =
  "inline-flex items-center justify-center gap-1.5 rounded-lg bg-slate-900 px-4 py-2.5 text-xs font-bold text-white shadow-xs hover:bg-slate-800 disabled:opacity-50 transition-colors sm:col-span-2 w-full sm:w-auto";
const label = "block text-xs font-bold text-slate-700";
const FREE_STARTER_STORAGE_BYTES_PER_SCHOOL = 100 * 1024 * 1024;
type LocalMutation = (args: Record<string, unknown>) => Promise<unknown>;
function lines(value: FormDataEntryValue | null) { return String(value ?? "").split("\n").map(row => row.trim()).filter(Boolean); }
function entitlement(form: FormData): UsageEntitlement {
  return {
    allowances: lines(form.get("allowances")).map(row => { const [meterType, baseUnits, graceUnits] = row.split(":"); if (meterType !== "ai_tokens" && meterType !== "ocr_pages" && meterType !== "storage_bytes") throw new Error("Allowance meter must be ai_tokens, ocr_pages or storage_bytes"); return { meterType, baseUnits: Number(baseUnits), graceUnits: Number(graceUnits) }; }),
    warningPercent: Number(form.get("warning")), criticalPercent: Number(form.get("critical")), hardStopPercent: Number(form.get("stop")), maxFileSizeBytes: Number(form.get("fileCap")), maxPagesPerOperation: Number(form.get("pageCap")),
    profiles: lines(form.get("profiles")).map(row => { const [task, meterType, unitsPerItem, maxItems, modelProfile] = row.split(":"); const tasks = ["teacher_lesson_plan", "provider_ocr", "knowledge_upload", "curriculum_generation", "ai_import"] as const; if (!tasks.includes(task as typeof tasks[number]) || (meterType !== "ai_tokens" && meterType !== "ocr_pages" && meterType !== "storage_bytes")) throw new Error("Invalid task profile line"); return { task: task as typeof tasks[number], meterType, unitsPerItem: Number(unitsPerItem), maxItems: Number(maxItems), modelProfile }; }),
  };
}
export function EntitlementControls({ schoolId, contractIds }: { schoolId: Id<"schools">; contractIds: Id<"commercialContracts">[] }) {
  const data = useQuery("functions/academic/usageEntitlements:getPlatformEntitlementWorkspace" as never, { schoolId } as never) as { versions: Array<{ _id: Id<"usageEntitlementVersions">; code: string; name: string; version: number; effectiveFrom: number; entitlement: UsageEntitlement }>; cycles: Array<{ _id: Id<"usageCycles">; code: string; version: number; startAt: number; endAt: number }>; requests: Array<{ _id: Id<"usageExceptionRequests">; units: number; meterType: string }>; storage: { status: "missing_entitlement" | "exhausted" | "ready"; allocatedBytes: number; availableBytes: number }; closingCycle: { _id: Id<"usageCycles">; code: string; endAt: number; meters: Array<{ meterType: "ai_tokens" | "ocr_pages" | "storage_bytes"; allocatedUnits: number; consumedUnits: number; reservedUnits: number }> } | null } | undefined;
  const publish = useMutation("functions/academic/usageEntitlements:publishEntitlementVersion" as never) as unknown as LocalMutation;
  const start = useMutation("functions/academic/usageEntitlements:startUsageCycle" as never) as unknown as LocalMutation;
  const close = useMutation("functions/academic/usageEntitlements:closeUsageCycle" as never) as unknown as LocalMutation;
  const grant = useMutation("functions/academic/usageEntitlements:recordTopUpGrant" as never) as unknown as LocalMutation;
  const decide = useMutation("functions/academic/usageEntitlements:decideUsageException" as never) as unknown as LocalMutation;
  const createPool = useMutation("functions/academic/usageEntitlements:createGroupPool" as never) as unknown as LocalMutation;
  const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  const [poolCreationId, setPoolCreationId] = useState(() => crypto.randomUUID());
  async function save(work: () => Promise<unknown>) { setPending(true); setMessage(""); try { await work(); setMessage("Recorded. No provider, payment or purchase was activated."); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "Save failed; values retained."); return false; } finally { setPending(false); } }
  if (!data) return <div className="bg-white rounded-xl border border-slate-200 shadow-xs p-5"><p role="status" className="text-sm text-slate-500">Loading entitlement configuration…</p></div>;
  return <section className="bg-white rounded-xl border border-slate-200 shadow-xs p-5 sm:p-6 space-y-4">
    <div>
      <h2 className="text-base font-bold text-slate-900">Versioned usage entitlements</h2>
      <p className="mt-1 text-sm text-slate-600">Allowance configuration is separate from subscription prices. Publishing does not grant a school allowance; a contract-bound cycle is required.</p>
      <p className="mt-1 text-xs text-slate-500">The Free/Starter-safe preset grants 100 MiB per school, keeping five schools at 500 MiB of Convex&apos;s 1 GB included file storage. Review provider usage before increasing it.</p>
      <p role="status" className="mt-2 inline-block rounded-lg bg-slate-50 border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700">Storage readiness: {data.storage.status === "ready" ? `${(data.storage.availableBytes / (1024 * 1024)).toFixed(1)} MiB available of ${(data.storage.allocatedBytes / (1024 * 1024)).toFixed(1)} MiB` : data.storage.status === "exhausted" ? "quota exhausted" : "no active contract-bound storage entitlement"}.</p>
      {message && <p role="status" className="mt-2 rounded-lg bg-slate-50 border border-slate-200 p-3 text-xs text-slate-700">{message}</p>}
    </div>
    <form className={formCard} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => publish({ journalSchoolId: schoolId, code: String(form.get("code")), name: String(form.get("name")), expectedVersion: Math.max(0, ...data.versions.filter(row => row.code === form.get("code")).map(row => row.version)), effectiveFrom: Date.parse(String(form.get("effectiveFrom"))), entitlement: entitlement(form), confirmation: String(form.get("confirmation")) })); }}>
      <div className="sm:col-span-2 text-xs font-bold text-slate-900">Publish entitlement version</div>
      <label className={label}><span className="mb-1 block">Entitlement code</span><input className={input} name="code" defaultValue="free_starter_storage" required /></label><label className={label}><span className="mb-1 block">Name</span><input className={input} name="name" defaultValue="Free / Starter storage" required /></label><label className={label}><span className="mb-1 block">Effective UTC date</span><input className={input} name="effectiveFrom" type="date" required /></label><label className={label}><span className="mb-1 block">Thresholds (warn / critical / stop)</span><div className="grid grid-cols-3 gap-2"><input className={input} aria-label="Notice threshold" name="warning" type="number" defaultValue={75} required /><input className={input} aria-label="Urgent threshold" name="critical" type="number" defaultValue={90} required /><input className={input} aria-label="Hard stop threshold" name="stop" type="number" defaultValue={100} required /></div></label><label className={label}><span className="mb-1 block">Max file bytes</span><input className={input} name="fileCap" type="number" defaultValue={12 * 1024 * 1024} required /></label><label className={label}><span className="mb-1 block">Max pages per operation</span><input className={input} name="pageCap" type="number" defaultValue={80} required /></label>
      <label className={label}><span className="mb-1 block">Allowances, one meter:base:grace per line</span><textarea className={input} name="allowances" rows={2} defaultValue={`storage_bytes:${FREE_STARTER_STORAGE_BYTES_PER_SCHOOL}:0`} required /></label><label className={label}><span className="mb-1 block">Task profiles, task:meter:unitsPerItem:maxItems:modelProfile</span><textarea className={input} name="profiles" rows={2} defaultValue={`knowledge_upload:storage_bytes:1:${12 * 1024 * 1024}:secure-upload`} required /></label><label className={label}><span className="mb-1 block">Type CONFIRM</span><input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending} className={primaryBtn}>Publish immutable entitlement version</button>
    </form>
    {data.versions.length > 0 && <div className="space-y-2">{data.versions.map(row => <p key={row._id} className="rounded-lg bg-slate-50 border border-slate-200 px-3 py-2 text-xs text-slate-700"><span className="font-bold text-slate-900">{row.name} v{row.version}</span> · effective {new Date(row.effectiveFrom).toISOString().slice(0, 10)} · {row.entitlement.allowances.map(a => `${a.meterType} ${a.baseUnits}+${a.graceUnits} grace`).join("; ")}</p>)}</div>}
    <form className={formCard} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => start({ schoolId, contractId: String(form.get("contractId")) as Id<"commercialContracts">, entitlementVersionId: String(form.get("versionId")) as Id<"usageEntitlementVersions">, startAt: Date.parse(String(form.get("start"))), endAt: Date.parse(String(form.get("end"))), confirmation: String(form.get("confirmation")) })); }}><h3 className="sm:col-span-2 text-xs font-bold text-slate-900">Start explicit cycle</h3><label className={label}><span className="mb-1 block">Contract</span><select className={input} name="contractId" required>{contractIds.map(id => <option key={id} value={id}>{id}</option>)}</select></label><label className={label}><span className="mb-1 block">Entitlement version</span><select className={input} name="versionId" required>{data.versions.map(row => <option key={row._id} value={row._id}>{row.code} v{row.version}</option>)}</select></label><label className={label}><span className="mb-1 block">Start UTC</span><input className={input} name="start" type="date" required /></label><label className={label}><span className="mb-1 block">End UTC, exclusive</span><input className={input} name="end" type="date" required /></label><label className={label}><span className="mb-1 block">Type CONFIRM</span><input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending || !contractIds.length || !data.versions.length} className={primaryBtn}>Start cycle</button></form>
    {data.cycles.length > 0 && <div className="space-y-2">{data.cycles.map(row => <p key={row._id} className="rounded-lg bg-slate-50 border border-slate-200 px-3 py-2 text-xs text-slate-700">Cycle {row.code} v{row.version}: {new Date(row.startAt).toISOString().slice(0, 10)}–{new Date(row.endAt).toISOString().slice(0, 10)}</p>)}</div>}
    {data.closingCycle && <form className={formCard} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => close({ schoolId, cycleId: data.closingCycle!._id, expectedMeters: data.closingCycle!.meters.map(({ meterType, allocatedUnits, consumedUnits }) => ({ meterType, allocatedUnits, consumedUnits })), reconciliationNote: String(form.get("note")), confirmation: String(form.get("confirmation")) })); }}>
      <h3 className="sm:col-span-2 text-xs font-bold text-slate-900">Close ended cycle {data.closingCycle.code}</h3>
      <p className="sm:col-span-2 text-xs text-slate-500">Ended {new Date(data.closingCycle.endAt).toISOString().slice(0, 10)}. Review every effective-at-close balance before starting another cycle.</p>
      <ul className="sm:col-span-2 space-y-1">{data.closingCycle.meters.map(meter => <li key={meter.meterType} className="rounded bg-white border border-slate-200 px-2 py-1 text-xs text-slate-600">{meter.meterType}: allocated {meter.allocatedUnits}, consumed {meter.consumedUnits}, reserved {meter.reservedUnits}</li>)}</ul>
      <label className={label}><span className="mb-1 block">Reconciliation note</span><input className={input} name="note" minLength={8} required /></label><label className={label}><span className="mb-1 block">Type CLOSE</span><input className={input} name="confirmation" pattern="CLOSE" required /></label><button disabled={pending || data.closingCycle.meters.some(meter => meter.reservedUnits !== 0)} className={primaryBtn}>Close reviewed cycle</button>
    </form>}
    <form className={formCard} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => grant({ schoolId, cycleId: String(form.get("cycleId")) as Id<"usageCycles">, meterType: String(form.get("meter")) as "ai_tokens" | "ocr_pages" | "storage_bytes", units: Number(form.get("units")), evidenceReference: String(form.get("reference")), reason: String(form.get("reason")), ...(form.get("expiry") ? { expiresAt: Date.parse(String(form.get("expiry"))) } : {}), confirmation: String(form.get("confirmation")) })); }}><h3 className="sm:col-span-2 text-xs font-bold text-slate-900">Record approved top-up grant (not a purchase)</h3><label className={label}><span className="mb-1 block">Cycle</span><select className={input} name="cycleId">{data.cycles.map(row => <option key={row._id} value={row._id}>{row.code} v{row.version}</option>)}</select></label><label className={label}><span className="mb-1 block">Meter</span><select className={input} name="meter"><option>ai_tokens</option><option>ocr_pages</option><option>storage_bytes</option></select></label><label className={label}><span className="mb-1 block">Units</span><input className={input} name="units" type="number" min={1} required /></label><label className={label}><span className="mb-1 block">Optional expiry</span><input className={input} name="expiry" type="date" /></label><label className={label}><span className="mb-1 block">Reviewed evidence reference</span><input className={input} name="reference" required /></label><label className={label}><span className="mb-1 block">Reason</span><input className={input} name="reason" required /></label><label className={label}><span className="mb-1 block">Type CONFIRM</span><input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending || !data.cycles.length} className={primaryBtn}>Record grant</button></form>
    <section className="rounded-xl bg-slate-50 border border-slate-200 p-4"><h3 className="text-xs font-bold text-slate-900">Exception decisions</h3>{!data.requests.length && <p className="mt-1 text-xs text-slate-500">No pending/recent exception requests.</p>}{data.requests.map(request => <form className="mt-2 grid gap-2 rounded-lg bg-white border border-slate-200 p-3 sm:grid-cols-2" key={request._id} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => decide({ schoolId, requestId: request._id, outcome: form.get("outcome") === "approved" ? "approved" : "declined", reason: String(form.get("reason")), confirmation: String(form.get("confirmation")) })); }}><p className="text-xs font-bold text-slate-900 sm:col-span-2">{request.units} {request.meterType}</p><label className={label}><span className="mb-1 block">Decision</span><select className={input} name="outcome"><option value="approved">Approve</option><option value="declined">Decline</option></select></label><label className={label}><span className="mb-1 block">Reason</span><input className={input} name="reason" required /></label><label className={label}><span className="mb-1 block">Type CONFIRM</span><input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending} className={primaryBtn}>Record append-only decision</button></form>)}</section>
    <form className={formCard} onSubmit={event => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); void save(() => createPool({ journalSchoolId: schoolId, groupId: String(form.get("groupId")) as Id<"schoolGroups">, entitlementVersionId: String(form.get("versionId")) as Id<"usageEntitlementVersions">, meterType: String(form.get("meter")) as "ai_tokens" | "ocr_pages" | "storage_bytes", idempotencyKey: poolCreationId, totalUnits: Number(form.get("units")), startAt: Date.parse(String(form.get("start"))), endAt: Date.parse(String(form.get("end"))), reason: String(form.get("reason")), confirmation: String(form.get("confirmation")) })).then(saved => { if (!saved) return; formElement.reset(); setPoolCreationId(crypto.randomUUID()); }); }}><h3 className="sm:col-span-2 text-xs font-bold text-slate-900">Create group pool</h3><label className={label}><span className="mb-1 block">Reviewed group ID</span><input className={input} name="groupId" required /></label><label className={label}><span className="mb-1 block">Entitlement version</span><select className={input} name="versionId">{data.versions.map(row => <option key={row._id} value={row._id}>{row.code} v{row.version}</option>)}</select></label><label className={label}><span className="mb-1 block">Meter</span><select className={input} name="meter"><option>ai_tokens</option><option>ocr_pages</option><option>storage_bytes</option></select></label><label className={label}><span className="mb-1 block">Total units</span><input className={input} name="units" type="number" min={1} required /></label><label className={label}><span className="mb-1 block">Start UTC</span><input className={input} name="start" type="date" required /></label><label className={label}><span className="mb-1 block">End UTC</span><input className={input} name="end" type="date" required /></label><label className={label}><span className="mb-1 block">Reason</span><input className={input} name="reason" required /></label><label className={label}><span className="mb-1 block">Type CONFIRM</span><input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending || !data.versions.length} className={primaryBtn}>Create pool without branch allocation</button></form>
  </section>;
}
