"use client";
import { useState } from "react";
import { useMutation, useQuery } from "convex/react";
import type { Id } from "../../../../packages/convex/_generated/dataModel";
import type { UsageEntitlement } from "../../../../packages/convex/functions/foundation/usageContract";
const input = "block w-full rounded border border-slate-300 p-2";
type LocalMutation = (args: Record<string, unknown>) => Promise<unknown>;
function lines(value: FormDataEntryValue | null) { return String(value ?? "").split("\n").map(row => row.trim()).filter(Boolean); }
function entitlement(form: FormData): UsageEntitlement {
  return {
    allowances: lines(form.get("allowances")).map(row => { const [meterType, baseUnits, graceUnits] = row.split(":"); if (meterType !== "ai_tokens" && meterType !== "ocr_pages" && meterType !== "storage_bytes") throw new Error("Allowance meter must be ai_tokens, ocr_pages or storage_bytes"); return { meterType, baseUnits: Number(baseUnits), graceUnits: Number(graceUnits) }; }),
    warningPercent: Number(form.get("warning")), criticalPercent: Number(form.get("critical")), hardStopPercent: Number(form.get("stop")), maxFileSizeBytes: Number(form.get("fileCap")), maxPagesPerOperation: Number(form.get("pageCap")),
    profiles: lines(form.get("profiles")).map(row => { const [task, meterType, unitsPerItem, maxItems, modelProfile] = row.split(":"); const tasks = ["teacher_lesson_plan", "provider_ocr", "knowledge_upload", "curriculum_generation", "ai_import"] as const; if (!tasks.includes(task as typeof tasks[number]) || (meterType !== "ai_tokens" && meterType !== "ocr_pages" && meterType !== "storage_bytes")) throw new Error("Invalid task profile line"); return { task: task as typeof tasks[number], meterType, unitsPerItem: Number(unitsPerItem), maxItems: Number(maxItems), modelProfile }; }),
  };
}
export function EntitlementControls({ schoolId, contractIds }: { schoolId: Id<"schools">; contractIds: Id<"commercialContracts">[] }) {
  const data = useQuery("functions/academic/usageEntitlements:getPlatformEntitlementWorkspace" as never, { schoolId } as never) as { versions: Array<{ _id: Id<"usageEntitlementVersions">; code: string; name: string; version: number; effectiveFrom: number; entitlement: UsageEntitlement }>; cycles: Array<{ _id: Id<"usageCycles">; code: string; version: number; startAt: number; endAt: number }>; requests: Array<{ _id: Id<"usageExceptionRequests">; units: number; meterType: string }> } | undefined;
  const publish = useMutation("functions/academic/usageEntitlements:publishEntitlementVersion" as never) as unknown as LocalMutation;
  const start = useMutation("functions/academic/usageEntitlements:startUsageCycle" as never) as unknown as LocalMutation;
  const grant = useMutation("functions/academic/usageEntitlements:recordTopUpGrant" as never) as unknown as LocalMutation;
  const decide = useMutation("functions/academic/usageEntitlements:decideUsageException" as never) as unknown as LocalMutation;
  const createPool = useMutation("functions/academic/usageEntitlements:createGroupPool" as never) as unknown as LocalMutation;
  const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  async function save(work: () => Promise<unknown>) { setPending(true); setMessage(""); try { await work(); setMessage("Recorded. No provider, payment or purchase was activated."); } catch (error) { setMessage(error instanceof Error ? error.message : "Save failed; values retained."); } finally { setPending(false); } }
  if (!data) return <p role="status">Loading entitlement configuration…</p>;
  return <section className="space-y-5 border-b pb-5"><h2 className="text-xl font-semibold">Versioned usage entitlements</h2><p>Allowance configuration is separate from subscription prices. Publishing does not grant a school allowance; a contract-bound cycle is required. No default plan limits are supplied.</p><p role="status">{message}</p>
    <form className="grid gap-2 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => publish({ journalSchoolId: schoolId, code: String(form.get("code")), name: String(form.get("name")), expectedVersion: Math.max(0, ...data.versions.filter(row => row.code === form.get("code")).map(row => row.version)), effectiveFrom: Date.parse(String(form.get("effectiveFrom"))), entitlement: entitlement(form), confirmation: String(form.get("confirmation")) })); }}>
      <label>Entitlement code<input className={input} name="code" required /></label><label>Name<input className={input} name="name" required /></label><label>Effective UTC date<input className={input} name="effectiveFrom" type="date" required /></label><label>Thresholds<input className={input} aria-label="Notice threshold" name="warning" type="number" placeholder="Notice %" required /><input className={input} aria-label="Urgent threshold" name="critical" type="number" placeholder="Urgent %" required /><input className={input} aria-label="Hard stop threshold" name="stop" type="number" placeholder="Hard stop %" required /></label><label>Max file bytes<input className={input} name="fileCap" type="number" required /></label><label>Max pages per operation<input className={input} name="pageCap" type="number" required /></label>
      <label>Allowances, one meter:base:grace per line<textarea className={input} name="allowances" placeholder="ai_tokens:base:grace" required /></label><label>Task profiles, task:meter:unitsPerItem:maxItems:modelProfile<textarea className={input} name="profiles" placeholder="teacher_lesson_plan:ai_tokens:units:maxItems:approved-profile" required /></label><label>Type CONFIRM<input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending}>Publish immutable entitlement version</button>
    </form>
    {data.versions.map(row => <p key={row._id}>{row.name} v{row.version} · effective {new Date(row.effectiveFrom).toISOString()} · {row.entitlement.allowances.map(a => `${a.meterType} ${a.baseUnits}+${a.graceUnits} grace`).join("; ")}</p>)}
    <form className="grid gap-2 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => start({ schoolId, contractId: String(form.get("contractId")) as Id<"commercialContracts">, entitlementVersionId: String(form.get("versionId")) as Id<"usageEntitlementVersions">, startAt: Date.parse(String(form.get("start"))), endAt: Date.parse(String(form.get("end"))), confirmation: String(form.get("confirmation")) })); }}><h3 className="sm:col-span-2 font-semibold">Start explicit cycle</h3><label>Contract<select className={input} name="contractId" required>{contractIds.map(id => <option key={id} value={id}>{id}</option>)}</select></label><label>Entitlement version<select className={input} name="versionId" required>{data.versions.map(row => <option key={row._id} value={row._id}>{row.code} v{row.version}</option>)}</select></label><label>Start UTC<input className={input} name="start" type="date" required /></label><label>End UTC, exclusive<input className={input} name="end" type="date" required /></label><label>Type CONFIRM<input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending || !contractIds.length || !data.versions.length}>Start cycle</button></form>
    {data.cycles.map(row => <p key={row._id}>Cycle {row.code} v{row.version}: {new Date(row.startAt).toISOString()}–{new Date(row.endAt).toISOString()}</p>)}
    <form className="grid gap-2 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => grant({ schoolId, cycleId: String(form.get("cycleId")) as Id<"usageCycles">, meterType: String(form.get("meter")) as "ai_tokens" | "ocr_pages" | "storage_bytes", units: Number(form.get("units")), evidenceReference: String(form.get("reference")), reason: String(form.get("reason")), ...(form.get("expiry") ? { expiresAt: Date.parse(String(form.get("expiry"))) } : {}), confirmation: String(form.get("confirmation")) })); }}><h3 className="sm:col-span-2 font-semibold">Record approved top-up grant (not a purchase)</h3><label>Cycle<select className={input} name="cycleId">{data.cycles.map(row => <option key={row._id} value={row._id}>{row.code} v{row.version}</option>)}</select></label><label>Meter<select className={input} name="meter"><option>ai_tokens</option><option>ocr_pages</option><option>storage_bytes</option></select></label><label>Units<input className={input} name="units" type="number" min={1} required /></label><label>Optional expiry<input className={input} name="expiry" type="date" /></label><label>Reviewed evidence reference<input className={input} name="reference" required /></label><label>Reason<input className={input} name="reason" required /></label><label>Type CONFIRM<input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending || !data.cycles.length}>Record grant</button></form>
    <section><h3 className="font-semibold">Exception decisions</h3>{!data.requests.length && <p>No pending/recent exception requests.</p>}{data.requests.map(request => <form className="grid gap-2 sm:grid-cols-4" key={request._id} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => decide({ schoolId, requestId: request._id, outcome: form.get("outcome") === "approved" ? "approved" : "declined", reason: String(form.get("reason")), confirmation: String(form.get("confirmation")) })); }}><p>{request.units} {request.meterType}</p><label>Decision<select className={input} name="outcome"><option value="approved">Approve</option><option value="declined">Decline</option></select></label><label>Reason<input className={input} name="reason" required /></label><label>Type CONFIRM<input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending}>Record append-only decision</button></form>)}</section>
    <form className="grid gap-2 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void save(() => createPool({ journalSchoolId: schoolId, groupId: String(form.get("groupId")) as Id<"schoolGroups">, entitlementVersionId: String(form.get("versionId")) as Id<"usageEntitlementVersions">, meterType: String(form.get("meter")) as "ai_tokens" | "ocr_pages" | "storage_bytes", totalUnits: Number(form.get("units")), startAt: Date.parse(String(form.get("start"))), endAt: Date.parse(String(form.get("end"))), reason: String(form.get("reason")), confirmation: String(form.get("confirmation")) })); }}><h3 className="sm:col-span-2 font-semibold">Create group pool</h3><label>Reviewed group ID<input className={input} name="groupId" required /></label><label>Entitlement version<select className={input} name="versionId">{data.versions.map(row => <option key={row._id} value={row._id}>{row.code} v{row.version}</option>)}</select></label><label>Meter<select className={input} name="meter"><option>ai_tokens</option><option>ocr_pages</option><option>storage_bytes</option></select></label><label>Total units<input className={input} name="units" type="number" min={1} required /></label><label>Start UTC<input className={input} name="start" type="date" required /></label><label>End UTC<input className={input} name="end" type="date" required /></label><label>Reason<input className={input} name="reason" required /></label><label>Type CONFIRM<input className={input} name="confirmation" pattern="CONFIRM" required /></label><button disabled={pending || !data.versions.length}>Create pool without branch allocation</button></form>
  </section>;
}
