import { createElement } from "react";
import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { AuthPanel, PublishedField } from "../components/AdmissionsApply";
import { answerPayload, availabilityMessage, conditionMatchesAnswers, correctionAllows, dateInputToUtcTimestamp, isDraftConflict, paymentMessage, validateSubmissionInput } from "../lib/journey";

const authMocks = vi.hoisted(() => ({ signUp: vi.fn(), signIn: vi.fn(), resend: vi.fn(), signOut: vi.fn() }));
vi.mock("@/lib/auth-client", () => ({ authClient: { useSession: () => ({ data: null, isPending: false }), signUp: { email: authMocks.signUp }, signIn: { email: authMocks.signIn }, sendVerificationEmail: authMocks.resend, signOut: authMocks.signOut } }));

describe("guardian email verification", () => {
  it("shows verification-pending and resend states after registration", async () => { authMocks.signUp.mockResolvedValue({ data: {}, error: null }); authMocks.resend.mockResolvedValue({ data: {}, error: null }); render(createElement(AuthPanel, { schoolSlug: "school" })); fireEvent.click(screen.getByRole("button", { name: "Create account" })); fireEvent.change(screen.getByLabelText("Your name"), { target: { value: "Guardian" } }); fireEvent.change(screen.getByLabelText("Email"), { target: { value: "guardian@example.test" } }); fireEvent.change(screen.getByLabelText("Password"), { target: { value: "secure-password" } }); fireEvent.click(screen.getByRole("button", { name: "Create account" })); expect(await screen.findByText(/Check your email, verify it/)).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Resend verification email" })); expect(await screen.findByText(/Verification email sent/)).toBeInTheDocument(); expect(authMocks.resend).toHaveBeenCalledWith({ email: "guardian@example.test", callbackURL: "/s/school/account" }); });
});

describe("public offering and payment truth", () => {
  it("explains every authoritative availability state", () => { expect(availabilityMessage("open")).toMatch(/open/); expect(availabilityMessage("upcoming", 1_800_000_000_000)).toMatch(/open/); expect(availabilityMessage("paused")).toMatch(/paused/); expect(availabilityMessage("closed")).toMatch(/closed/); expect(availabilityMessage("unavailable")).toMatch(/unavailable/); });
  it("does not describe pending, refunded, or reversed attempts as paid", () => { expect(paymentMessage("checkout_pending")).toMatch(/pending provider verification/); expect(paymentMessage("paid")).toMatch(/verified/); expect(paymentMessage("refunded")).toMatch(/refunded/); expect(paymentMessage("reversed")).toMatch(/reversed/); expect(paymentMessage("manual_attention")).toMatch(/no paid slot/); });
});

describe("application draft, correction, and submission", () => {
  it("stores date-only values at UTC midnight without a local-time shift", () => { expect(dateInputToUtcTimestamp("2026-04-02")).toBe(Date.UTC(2026, 3, 2)); });
  it("classifies draft conflicts and serializes supported published field values", () => { expect(isDraftConflict(new Error("DRAFT_VERSION_CONFLICT"))).toBe(true); expect(answerPayload("number", "12")).toEqual({ valueType: "number", serializedValue: "12" }); expect(answerPayload("boolean", "true")).toEqual({ valueType: "boolean", serializedValue: "true" }); expect(answerPayload("multi_select", "A, B").serializedValue).toBe('["A","B"]'); expect(answerPayload("date", "2026-04-02")).toEqual({ valueType: "date", serializedValue: String(Date.parse("2026-04-02T00:00:00Z")) }); });
  it("limits changes-requested editing to the backend correction scope", () => { expect(correctionAllows("draft", undefined, "profile")).toBe(true); expect(correctionAllows("changes_requested", ["profile"], "profile")).toBe(true); expect(correctionAllows("changes_requested", ["profile"], "primaryContact")).toBe(false); expect(correctionAllows("submitted", ["profile"], "profile")).toBe(false); });
  it("requires signer, relationship, and declaration before submission", () => { expect(validateSubmissionInput({ signerName: "", signerRelationship: "Parent", declarationAccepted: true })).toMatch(/signer name/); expect(validateSubmissionInput({ signerName: "Guardian", signerRelationship: "", declarationAccepted: true })).toMatch(/relationship/); expect(validateSubmissionInput({ signerName: "Guardian", signerRelationship: "Parent", declarationAccepted: false })).toMatch(/declaration/); expect(validateSubmissionInput({ signerName: "Guardian", signerRelationship: "Parent", declarationAccepted: true })).toBeNull(); });
});

describe("conditional and typed published fields", () => {
  it("matches conditional rules against typed controlling answers", () => { const kinds = new Map([["hasSibling", "boolean"], ["count", "number"]]); expect(conditionMatchesAnswers('{"fieldKey":"hasSibling","operator":"equals","value":true}', { hasSibling: "true" }, kinds)).toBe(true); expect(conditionMatchesAnswers('{"fieldKey":"count","operator":"equals","value":2}', { count: "1" }, kinds)).toBe(false); });
  it("renders real choice controls and purpose/sensitivity guidance", () => { const onChange = vi.fn(); render(createElement(PublishedField, { field: { fieldKey: "choice", sectionKey: "details", kind: "select", label: "Preferred language", helpText: "Choose one", requiredMode: "required", dataClass: "personal", purpose: "Plan support", validationJson: '{"options":["English","French"]}', conditionalRuleJson: null, order: 1 }, value: "", disabled: false, onChange })); const control = screen.getByLabelText(/Preferred language/); expect(control.tagName).toBe("SELECT"); expect(screen.getByText("French")).toBeInTheDocument(); expect(screen.getByText(/Purpose: Plan support/)).toHaveTextContent(/Sensitive data: personal/); fireEvent.change(control, { target: { value: "French" } }); expect(onChange).toHaveBeenCalledWith("French"); });
  it("renders boolean and multi-select controls with typed interactions", () => { const onBoolean = vi.fn(); const { unmount } = render(createElement(PublishedField, { field: { fieldKey: "consent", sectionKey: "details", kind: "boolean", label: "Consent", helpText: null, requiredMode: "optional", dataClass: "public", purpose: null, validationJson: "{}", conditionalRuleJson: null, order: 1 }, value: "", disabled: false, onChange: onBoolean })); fireEvent.change(screen.getByLabelText(/Consent/), { target: { value: "true" } }); expect(onBoolean).toHaveBeenCalledWith("true"); unmount(); const onMulti = vi.fn(); render(createElement(PublishedField, { field: { fieldKey: "clubs", sectionKey: "details", kind: "multi_select", label: "Clubs", helpText: null, requiredMode: "optional", dataClass: "public", purpose: null, validationJson: '{"options":["Art","Music"]}', conditionalRuleJson: null, order: 1 }, value: "Art", disabled: false, onChange: onMulti })); const select = screen.getByLabelText(/Clubs/) as HTMLSelectElement; for (const option of select.options) option.selected = true; fireEvent.change(select); expect(onMulti).toHaveBeenCalledWith("Art, Music"); });
});

describe("secure upload route contract", () => {
  it("rejects missing, invalid, and oversized Content-Length before reading a body", async () => { const { POST } = await import("../app/admissions/document-upload/route"); expect((await POST(new Request("http://localhost/admissions/document-upload", { method: "POST", body: "x" }))).status).toBe(411); expect((await POST(new Request("http://localhost/admissions/document-upload", { method: "POST", headers: { "content-length": String(21 * 1024 * 1024) }, body: "x" }))).status).toBe(413); });
});
