import { createElement, type ComponentProps } from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { EMPTY_CAMPAIGN, nextCampaignDefinitionKey, parseDefinitions, slugifyCampaignValue, validateCampaign, validateRetention } from "../app/admin/admissions/admissions-model";
import { getAccessibleWorkspaceSections, getBranchScopedWorkspaceAccess, getWorkspaceCapabilityDenial, getWorkspaceModuleDenial, isWorkspaceBranchScopedRoute, WorkspaceNavbar, type WorkspaceAccessSummary } from "@school/shared";

const mocks = vi.hoisted(() => ({ queryResult: undefined as unknown, eligibility: undefined as unknown, mutate: vi.fn(), editParam: null as string | null, replace: vi.fn() }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ replace: mocks.replace }), usePathname: () => "/admin/admissions", useSearchParams: () => new URLSearchParams(mocks.editParam ? { edit: mocks.editParam } : {}) }));
vi.mock("convex/react", () => ({ useQuery: (_ref: unknown, args: unknown) => args === "skip" ? undefined : args && typeof args === "object" && "paginationOpts" in args ? { page: [], isDone: true, continueCursor: "" } : args && typeof args === "object" && "documentKey" in args ? mocks.eligibility : mocks.queryResult, useMutation: () => mocks.mutate }));
vi.mock("@/AuthProvider", () => ({ useAuth: () => ({ workspaceAccess: access(["enrollment.intakes.manage", "enrollment.applications.list", "enrollment.applications.view_basic", "enrollment.documents.review", "enrollment.decisions.record", "finance.fee_plans.manage"]) }) }));
vi.mock("@school/shared/toast", () => ({ appToast: { success: vi.fn(), error: vi.fn() } }));

const valid = { ...EMPTY_CAMPAIGN, programmeSlug: "primary", programmeName: "Primary", intakeSlug: "intake", intakeName: "Intake", cycleLabel: "Cycle", opensAt: "2026-01-01T09:00", closesAt: "2026-02-01T09:00", declarationTitle: "Declaration", declarationBody: "Confirm details", declarationPurpose: "Attestation", productSlug: "slot", productName: "Application slot", amount: "5000", currency: "NGN", refundPolicyKey: "policy", feeDisclosure: "Published fee disclosure" };
import { AdmissionsDashboard } from "../app/admin/admissions/AdmissionsDashboard";
import { RetentionSettings } from "../app/admin/admissions/retention/RetentionSettings";
import { admissionsAdminErrorMessage, DocumentRow } from "../app/admin/admissions/[publicId]/ApplicationDetail";

function access(capabilities: string[]): WorkspaceAccessSummary { return { state: "ready", branch: { schoolId: "school", name: "School", slug: "school", status: "active" }, membership: { membershipId: "member", personId: "person", displayTitle: null, isProprietor: false }, displayTitle: null, effectiveCapabilities: capabilities, compatibility: { mode: "canonical", permissionManaged: true, legacyUserId: "user", legacyRole: "admin", legacyIsSchoolAdmin: true, adminParity: "review_required", legacyDefaultSchoolId: "school" }, teacherAssignments: { source: "domain_checks_required", legacyTeacherId: null } }; }

describe("admin admissions campaign and retention UI contracts", () => {
  beforeEach(() => { mocks.queryResult = []; mocks.eligibility = undefined; mocks.mutate.mockReset().mockResolvedValue({ programmeId: "programme", intakeId: "intake", formVersionId: "form", declarationVersionId: "declaration", productId: "product", priceId: "price", draftRevision: "campaign-draft-v1:form:1", version: 2, changed: true }); });
  it("creates a usable campaign from guided defaults and keeps the editor open", async () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); fireEvent.change(screen.getByLabelText("Programme name"), { target: { value: "Primary School" } }); fireEvent.change(screen.getByLabelText("Intake name"), { target: { value: "2027 Main Intake" } }); fireEvent.change(screen.getByLabelText("Amount"), { target: { value: "5000" } }); expect(screen.getByText("primary-school")).toBeInTheDocument(); expect(screen.getByText("2027-main-intake")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "Save draft" })); await waitFor(() => expect(mocks.mutate).toHaveBeenCalled()); expect(screen.getByRole("heading", { name: "Set up an admissions campaign" })).toBeInTheDocument(); expect(screen.getByRole("status")).toHaveTextContent(/remains open/); });
  it("builds extra questions without requiring JSON editing", () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); fireEvent.click(screen.getByRole("button", { name: "Add question" })); fireEvent.change(screen.getByLabelText("Question"), { target: { value: "Previous school" } }); fireEvent.click(screen.getByRole("switch", { name: "Required" })); expect(screen.getByLabelText("Question")).toHaveValue("Previous school"); expect(screen.getByRole("switch", { name: "Required" })).toHaveAttribute("aria-checked", "true"); expect(screen.queryByText("Question definition JSON")).not.toBeInTheDocument(); });
  it("snaps only the inner scroll container to the editor on open", () => { const view = render(createElement(AdmissionsDashboard)); const scroller = view.container; scroller.style.overflowY = "auto"; Object.defineProperties(scroller, { scrollHeight: { value: 2000, configurable: true }, clientHeight: { value: 800, configurable: true } }); const scrollTo = vi.fn(); Object.defineProperty(scroller, "scrollTo", { value: scrollTo, configurable: true }); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); expect(screen.getByRole("heading", { name: "Set up an admissions campaign" })).toBeInTheDocument(); expect(scrollTo).toHaveBeenCalledWith({ top: 0, behavior: "smooth" }); });
  it("does not scroll again when saving keeps the editor open", async () => { const view = render(createElement(AdmissionsDashboard)); const scroller = view.container; scroller.style.overflowY = "auto"; Object.defineProperties(scroller, { scrollHeight: { value: 2000, configurable: true }, clientHeight: { value: 800, configurable: true } }); const scrollTo = vi.fn(); Object.defineProperty(scroller, "scrollTo", { value: scrollTo, configurable: true }); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); expect(scrollTo).toHaveBeenCalledTimes(1); fireEvent.change(screen.getByLabelText("Programme name"), { target: { value: "Primary School" } }); fireEvent.change(screen.getByLabelText("Intake name"), { target: { value: "2027 Main Intake" } }); fireEvent.change(screen.getByLabelText("Amount"), { target: { value: "5000" } }); fireEvent.click(screen.getByRole("button", { name: "Save draft" })); await waitFor(() => expect(mocks.mutate).toHaveBeenCalled()); expect(scrollTo).toHaveBeenCalledTimes(1); });
  it("reorders questions without losing their content", () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); fireEvent.click(screen.getByRole("button", { name: "Add question" })); fireEvent.click(screen.getByRole("button", { name: "Add question" })); const inputs = screen.getAllByLabelText("Question"); fireEvent.change(inputs[0], { target: { value: "First" } }); fireEvent.change(inputs[1], { target: { value: "Second" } }); fireEvent.click(screen.getAllByRole("button", { name: "Move question down" })[0]); expect(screen.getAllByLabelText("Question").map((element) => (element as HTMLInputElement).value)).toEqual(["Second", "First"]); });
  it("edits choice options as separate rows that keep spaces", () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); fireEvent.click(screen.getByRole("button", { name: "Add question" })); fireEvent.change(screen.getByLabelText("Answer type"), { target: { value: "select" } }); fireEvent.change(screen.getByLabelText("Option 1"), { target: { value: "Yes please" } }); expect(screen.getByLabelText("Option 1")).toHaveValue("Yes please"); fireEvent.click(screen.getByRole("button", { name: "Add option" })); expect(screen.getByLabelText("Option 3")).toBeInTheDocument(); });
  it("centers the moved card in view with a highlight", () => { const view = render(createElement(AdmissionsDashboard)); const scroller = view.container; scroller.style.overflowY = "auto"; Object.defineProperties(scroller, { scrollHeight: { value: 2000, configurable: true }, clientHeight: { value: 800, configurable: true } }); const scrollTo = vi.fn(); Object.defineProperty(scroller, "scrollTo", { value: scrollTo, configurable: true }); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); fireEvent.click(screen.getByRole("button", { name: "Add question" })); fireEvent.click(screen.getByRole("button", { name: "Add question" })); fireEvent.click(screen.getAllByRole("button", { name: "Move question down" })[0]); expect(scrollTo).toHaveBeenLastCalledWith({ top: 0, behavior: "smooth" }); expect(document.querySelector("[data-card-key].ring-2")).toBeTruthy(); expect(document.querySelectorAll("section.bg-transparent").length).toBeGreaterThan(0); });
  it("duplicates a question with a fresh key and focuses the copy", () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); fireEvent.click(screen.getByRole("button", { name: "Add question" })); fireEvent.change(screen.getByLabelText("Question"), { target: { value: "Original" } }); fireEvent.click(screen.getByRole("button", { name: "Duplicate question" })); const inputs = screen.getAllByLabelText("Question"); expect(inputs.map((element) => (element as HTMLInputElement).value)).toEqual(["Original", "Original"]); const keys = [...document.querySelectorAll("[data-card-key]")].map((element) => element.getAttribute("data-card-key")); expect(new Set(keys).size).toBe(2); });
  it("highlights the card being edited", () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); fireEvent.click(screen.getByRole("button", { name: "Add question" })); fireEvent.focus(screen.getByLabelText("Question")); expect(document.querySelector("[data-card-key].ring-2")).toBeTruthy(); });
  it("renders document cards with the same toolbar language as questions", () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); fireEvent.click(screen.getByRole("button", { name: "Add document" })); expect(screen.getByLabelText("Document name")).toBeInTheDocument(); expect(screen.getByLabelText("Category")).toBeInTheDocument(); expect(screen.getByLabelText("Maximum size")).toBeInTheDocument(); fireEvent.click(screen.getByRole("switch", { name: "Required document" })); expect(screen.getByRole("switch", { name: "Required document" })).toHaveAttribute("aria-checked", "true"); fireEvent.click(screen.getByRole("button", { name: "Duplicate document" })); expect(screen.getAllByLabelText("Document name")).toHaveLength(2); });
  it("hides the application queue while the editor is open", () => { render(createElement(AdmissionsDashboard)); expect(screen.getByText("Application queue")).toBeInTheDocument(); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); expect(screen.queryByText("Application queue")).toBeNull(); fireEvent.click(screen.getByRole("button", { name: "Cancel" })); expect(screen.getByText("Application queue")).toBeInTheDocument(); });
  it("shows parents' built-in details next to extra questions", () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); expect(screen.getByText("See the details parents already fill in")).toBeInTheDocument(); expect(screen.getByText("Middle name, gender, preferred name")).toBeInTheDocument(); });
  it("opens the editor from a shared draft link", () => { mocks.editParam = "new"; render(createElement(AdmissionsDashboard)); expect(screen.getByRole("heading", { name: "Set up an admissions campaign" })).toBeInTheDocument(); mocks.editParam = null; });
  it("writes the draft id to the URL when the editor opens and clears it on cancel", () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); expect(mocks.replace).toHaveBeenCalledWith("/admin/admissions?edit=new"); fireEvent.click(screen.getByRole("button", { name: "Cancel" })); expect(mocks.replace).toHaveBeenCalledWith("/admin/admissions"); });
  it("offers add buttons at the end of non-empty sections", () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); expect(screen.queryByRole("button", { name: "Add another question" })).toBeNull(); fireEvent.click(screen.getByRole("button", { name: "Add question" })); fireEvent.click(screen.getByRole("button", { name: "Add another question" })); expect(screen.getAllByLabelText("Question")).toHaveLength(2); expect(document.querySelectorAll("fieldset.min-w-0").length).toBeGreaterThan(0); fireEvent.click(screen.getByRole("button", { name: "Add document" })); fireEvent.click(screen.getByRole("button", { name: "Add another document" })); expect(screen.getAllByLabelText("Document name")).toHaveLength(2); });
  it("reloads all server values after a stale campaign conflict", async () => { const campaign = { programmeId: "programme", intakeId: "intake", formVersionId: "form", declarationVersionId: "declaration", productId: "product", priceId: "price", lifecycle: "draft", draftRevision: "campaign-draft-v1:form:1", applicationLink: { version: "1", schoolSlug: "school", intakeSlug: "2027", href: "https://apply.example.test/s/school/i/2027", availability: "unavailable", opensAt: Date.parse(valid.opensAt), closesAt: Date.parse(valid.closesAt) }, programmeSlug: valid.programmeSlug, programmeName: valid.programmeName, programmeDescription: null, intakeSlug: valid.intakeSlug, intakeName: valid.intakeName, cycleLabel: valid.cycleLabel, opensAt: Date.parse(valid.opensAt), closesAt: Date.parse(valid.closesAt), startsAt: null, schemaVersion: "1", formVersion: 1, declarationTitle: valid.declarationTitle, declarationBody: valid.declarationBody, declarationPurpose: valid.declarationPurpose, productSlug: valid.productSlug, productName: valid.productName, amountMinor: 500000, currency: valid.currency, refundPolicyKey: valid.refundPolicyKey, feeDisclosure: valid.feeDisclosure, effectiveFrom: Date.now(), effectiveTo: null, fields: [], requirements: [] }; mocks.queryResult = [campaign]; mocks.mutate.mockRejectedValueOnce(new Error("CAMPAIGN_DRAFT_CONFLICT")); const view = render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "Edit" })); fireEvent.change(screen.getByLabelText("Programme name"), { target: { value: "Local edit" } }); fireEvent.click(screen.getByRole("button", { name: "Save draft" })); await screen.findByRole("button", { name: "Reload all server values" }); expect(mocks.mutate).toHaveBeenCalledWith(expect.objectContaining({ effectiveFrom: campaign.effectiveFrom })); mocks.queryResult = [{ ...campaign, programmeName: "Server edit", draftRevision: "campaign-draft-v1:form:2" }]; view.rerender(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "Reload all server values" })); expect(screen.getByLabelText("Programme name")).toHaveValue("Server edit"); });
  it("shows accessible copy and open controls for a published canonical Apply link", async () => { const clipboard = vi.fn().mockResolvedValue(undefined); Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: clipboard } }); mocks.queryResult = [{ programmeId: "programme", intakeId: "intake", formVersionId: "form", declarationVersionId: "declaration", productId: "product", priceId: "price", lifecycle: "published", draftRevision: "published", applicationLink: { version: "1", schoolSlug: "school", intakeSlug: "2027", href: "https://apply.example.test/s/school/i/2027", availability: "open", opensAt: 1, closesAt: 2 }, programmeSlug: "primary", programmeName: "Primary", programmeDescription: null, intakeSlug: "2027", intakeName: "2027", cycleLabel: "2027", opensAt: 1, closesAt: 2, startsAt: null, schemaVersion: "1", formVersion: 1, declarationTitle: "Declaration", declarationBody: "Body", declarationPurpose: "Purpose", productSlug: "slot", productName: "Slot", amountMinor: 5000, currency: "NGN", refundPolicyKey: "policy", feeDisclosure: "fee", effectiveFrom: 1, effectiveTo: null, fields: [], requirements: [] }]; render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "Copy Apply link" })); await waitFor(() => expect(clipboard).toHaveBeenCalledWith("https://apply.example.test/s/school/i/2027")); expect(screen.getByRole("link", { name: "Open Apply link" })).toHaveAttribute("href", "https://apply.example.test/s/school/i/2027"); });
  it("renders separate retention labels and confirms permanent deletion", async () => { mocks.queryResult = { mode: "never", archiveAfterDays: null, version: 1, effectiveFrom: 1 }; mocks.eligibility = { state: "archived", canArchive: false, canDelete: true, archiveBlocker: "DOCUMENT_ALREADY_ARCHIVED", deleteBlocker: null }; render(createElement(RetentionSettings)); expect(screen.getByLabelText("Never automatically archive")).toBeChecked(); expect(screen.getByLabelText("Archive delay in days")).toHaveAttribute("min", "30"); fireEvent.change(screen.getByLabelText("Document key"), { target: { value: "document-1" } }); fireEvent.click(screen.getByRole("button", { name: "Check eligibility" })); fireEvent.click(await screen.findByRole("button", { name: "Permanently delete document" })); expect(screen.getByRole("dialog")).toHaveTextContent("Permanently delete this document?"); });
  it("validates paid campaign drafts, dates, JSON definitions, and replacement-ready definitions", () => { expect(validateCampaign(valid)).toEqual([]); expect(parseDefinitions(valid)).toEqual({ fields: [], requirements: [] }); expect(nextCampaignDefinitionKey("question", ["question-2", "question-1"])).toBe("question-3"); expect(nextCampaignDefinitionKey("document", ["document-2"])).toBe("document-1"); expect(slugifyCampaignValue(" 2027 Main Intake ")).toBe("2027-main-intake"); expect(validateCampaign({ ...valid, amount: "0", closesAt: valid.opensAt }).join(" ")).toMatch(/after opening|greater than zero/); expect(() => parseDefinitions({ ...valid, fieldsJson: "{}" })).toThrow(/JSON arrays/); });
  it("enforces never or integer archive minimum", () => { expect(validateRetention("never", "")).toBeNull(); expect(validateRetention("archive", "29")).toMatch(/at least 30/); expect(validateRetention("archive", "30.5")).toMatch(/integer/); expect(validateRetention("archive", "30")).toBeNull(); });
  it("renders document metadata without hashes or internal keys and opens only the Melo proxy URL", async () => {
    const proxyUrl = `/api/admissions/documents/${"c".repeat(64)}`;
    const assign = vi.fn();
    const close = vi.fn();
    const openedWindow = { location: { assign }, close, opener: window } as unknown as Window;
    const open = vi.spyOn(window, "open").mockImplementation(() => openedWindow);
    mocks.mutate.mockResolvedValue({ status: "available", url: proxyUrl, expiresAt: Date.now() + 60_000 });
    const view = render(createElement(DocumentRow, { schoolId: "school" as never, document: { documentKey: "internal-document-key", requirementId: null, category: "medical", fileName: "medical.pdf", mimeType: "application/pdf", byteSize: 42, version: 1, submittedState: "uploaded", currentState: "uploaded", sensitivity: "highly_sensitive" }, canReview: true, onFeedback: vi.fn() }));
    expect(view.container.textContent).not.toMatch(/internal-document-key|sha-256|private-hash|convex\.cloud|api\/storage/i);
    fireEvent.click(screen.getByRole("button", { name: "View" }));
    expect(open).toHaveBeenCalledWith("about:blank", "_blank");
    await waitFor(() => expect(assign).toHaveBeenCalledWith(proxyUrl));
    expect(close).not.toHaveBeenCalled();
    expect(admissionsAdminErrorMessage(new Error("[CONVEX M(...)] ConvexError: internal-document-key Called by client"))).toBe("The operation could not be completed safely. Review the current workflow state and try again.");
  });
});

describe("admissions navigation and route capability gates", () => {
  it("renders Admissions in the shared Admin navigation when enabled", () => { const navbarProps: ComponentProps<typeof WorkspaceNavbar> = { workspace: "admin", currentPath: "/admin/dashboard", workspaceAccess: access(["enrollment.applications.list"]), schoolBranding: { name: "School", features: { admissions: true } }, renderLink: (props) => createElement("a", { key: props.href, href: props.href }, props.children), children: createElement("p", null, "Workspace") }; render(createElement(WorkspaceNavbar, navbarProps)); expect(screen.getByRole("link", { name: "Admissions" })).toHaveAttribute("href", "/admin/admissions"); });
  it("makes admissions discoverable only with route capability and active module", () => { const allowed = access(["enrollment.applications.list"]); expect(getAccessibleWorkspaceSections("admin", { access: allowed, features: { admissions: true } }).some((item) => item.href === "/admin/admissions")).toBe(true); expect(getWorkspaceCapabilityDenial("admin", "/admin/admissions", access([]))?.state).toBe("forbidden"); expect(getWorkspaceModuleDenial("admin", "/admin/admissions", { admissions: false })?.state).toBe("module_disabled"); expect(getWorkspaceModuleDenial("admin", "/admin/admissions", {})?.state).toBe("module_disabled"); });
  it("gates queue, detail, and retention routes through the shared matrix", () => { expect(isWorkspaceBranchScopedRoute("admin", "/admin/admissions/example")).toBe(true); expect(getBranchScopedWorkspaceAccess("admin", "/admin/admissions/example", access(["enrollment.applications.view_basic"])).state).toBe("allowed"); expect(getBranchScopedWorkspaceAccess("admin", "/admin/admissions/retention", access(["enrollment.applications.view_basic"])).state).toBe("forbidden"); expect(getBranchScopedWorkspaceAccess("admin", "/admin/admissions/retention", access(["enrollment.intakes.manage"])).state).toBe("forbidden"); expect(getBranchScopedWorkspaceAccess("admin", "/admin/admissions/retention", access(["enrollment.intakes.manage", "enrollment.decisions.record"])).state).toBe("allowed"); });
});
