import { createElement } from "react";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { EMPTY_CAMPAIGN, parseDefinitions, validateCampaign, validateRetention } from "../app/admin/admissions/admissions-model";
import { getAccessibleWorkspaceSections, getBranchScopedWorkspaceAccess, getWorkspaceCapabilityDenial, getWorkspaceModuleDenial, isWorkspaceBranchScopedRoute, type WorkspaceAccessSummary } from "@school/shared";

const mocks = vi.hoisted(() => ({ queryResult: undefined as unknown, eligibility: undefined as unknown, mutate: vi.fn() }));
vi.mock("convex/react", () => ({ useQuery: (_ref: unknown, args: unknown) => args === "skip" ? undefined : args && typeof args === "object" && "paginationOpts" in args ? { page: [], isDone: true, continueCursor: "" } : args && typeof args === "object" && "documentKey" in args ? mocks.eligibility : mocks.queryResult, useMutation: () => mocks.mutate }));
vi.mock("@/AuthProvider", () => ({ useAuth: () => ({ workspaceAccess: access(["enrollment.intakes.manage", "enrollment.applications.list", "enrollment.applications.view_basic", "enrollment.documents.review", "enrollment.decisions.record"]) }) }));
vi.mock("@school/shared/toast", () => ({ appToast: { success: vi.fn(), error: vi.fn() } }));

const valid = { ...EMPTY_CAMPAIGN, programmeSlug: "primary", programmeName: "Primary", intakeSlug: "intake", intakeName: "Intake", cycleLabel: "Cycle", opensAt: "2026-01-01T09:00", closesAt: "2026-02-01T09:00", declarationTitle: "Declaration", declarationBody: "Confirm details", declarationPurpose: "Attestation", productSlug: "slot", productName: "Application slot", amount: "5000", currency: "NGN", refundPolicyKey: "policy", feeDisclosure: "Published fee disclosure" };
import { AdmissionsDashboard } from "../app/admin/admissions/AdmissionsDashboard";
import { RetentionSettings } from "../app/admin/admissions/retention/RetentionSettings";

function access(capabilities: string[]): WorkspaceAccessSummary { return { state: "ready", branch: { schoolId: "school", name: "School", slug: "school", status: "active" }, membership: { membershipId: "member", personId: "person", displayTitle: null, isProprietor: false }, displayTitle: null, effectiveCapabilities: capabilities, compatibility: { mode: "canonical", permissionManaged: true, legacyUserId: "user", legacyRole: "admin", legacyIsSchoolAdmin: true, adminParity: "review_required", legacyDefaultSchoolId: "school" }, teacherAssignments: { source: "domain_checks_required", legacyTeacherId: null } }; }

describe("admin admissions campaign and retention UI contracts", () => {
  beforeEach(() => { mocks.queryResult = []; mocks.eligibility = undefined; mocks.mutate.mockReset().mockResolvedValue({ programmeId: "programme", intakeId: "intake", formVersionId: "form", declarationVersionId: "declaration", productId: "product", priceId: "price", draftRevision: "campaign-draft-v1:form:1", version: 2, changed: true }); });
  it("keeps a newly created campaign editor open after its first save", async () => { render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "New campaign" })); const values: Record<string, string> = { "Programme slug": "primary", "Programme name": "Primary", "Intake slug": "2027", "Intake name": "2027 Intake", "Cycle label": "2027/28", "Opens": "2027-01-01T09:00", "Closes": "2027-02-01T09:00", "Product slug": "slot", "Fee product name": "Application slot", "Fee amount": "5000", "Currency": "NGN", "Refund policy key": "policy", "Declaration title": "Declaration", "Declaration body": "I confirm", "Declaration purpose": "Attestation", "Fee disclosure": "Processing fee" }; for (const [label, value] of Object.entries(values)) fireEvent.change(screen.getByLabelText(label), { target: { value } }); fireEvent.click(screen.getByRole("button", { name: "Save draft" })); await waitFor(() => expect(mocks.mutate).toHaveBeenCalled()); expect(screen.getByRole("heading", { name: "Campaign draft" })).toBeInTheDocument(); expect(screen.getByRole("status")).toHaveTextContent(/remains open/); });
  it("reloads all server values after a stale campaign conflict", async () => { const campaign = { programmeId: "programme", intakeId: "intake", formVersionId: "form", declarationVersionId: "declaration", productId: "product", priceId: "price", lifecycle: "draft", draftRevision: "campaign-draft-v1:form:1", applicationLink: { version: "1", schoolSlug: "school", intakeSlug: "2027", href: "https://apply.example.test/s/school/i/2027", availability: "unavailable", opensAt: Date.parse(valid.opensAt), closesAt: Date.parse(valid.closesAt) }, programmeSlug: valid.programmeSlug, programmeName: valid.programmeName, programmeDescription: null, intakeSlug: valid.intakeSlug, intakeName: valid.intakeName, cycleLabel: valid.cycleLabel, opensAt: Date.parse(valid.opensAt), closesAt: Date.parse(valid.closesAt), startsAt: null, schemaVersion: "1", formVersion: 1, declarationTitle: valid.declarationTitle, declarationBody: valid.declarationBody, declarationPurpose: valid.declarationPurpose, productSlug: valid.productSlug, productName: valid.productName, amountMinor: 500000, currency: valid.currency, refundPolicyKey: valid.refundPolicyKey, feeDisclosure: valid.feeDisclosure, effectiveFrom: Date.now(), effectiveTo: null, fields: [], requirements: [] }; mocks.queryResult = [campaign]; mocks.mutate.mockRejectedValueOnce(new Error("CAMPAIGN_DRAFT_CONFLICT")); const view = render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "Edit" })); fireEvent.change(screen.getByLabelText("Programme name"), { target: { value: "Local edit" } }); fireEvent.click(screen.getByRole("button", { name: "Save draft" })); await screen.findByRole("button", { name: "Reload all server values" }); mocks.queryResult = [{ ...campaign, programmeName: "Server edit", draftRevision: "campaign-draft-v1:form:2" }]; view.rerender(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "Reload all server values" })); expect(screen.getByLabelText("Programme name")).toHaveValue("Server edit"); });
  it("shows accessible copy and open controls for a published canonical Apply link", async () => { const clipboard = vi.fn().mockResolvedValue(undefined); Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: clipboard } }); mocks.queryResult = [{ programmeId: "programme", intakeId: "intake", formVersionId: "form", declarationVersionId: "declaration", productId: "product", priceId: "price", lifecycle: "published", draftRevision: "published", applicationLink: { version: "1", schoolSlug: "school", intakeSlug: "2027", href: "https://apply.example.test/s/school/i/2027", availability: "open", opensAt: 1, closesAt: 2 }, programmeSlug: "primary", programmeName: "Primary", programmeDescription: null, intakeSlug: "2027", intakeName: "2027", cycleLabel: "2027", opensAt: 1, closesAt: 2, startsAt: null, schemaVersion: "1", formVersion: 1, declarationTitle: "Declaration", declarationBody: "Body", declarationPurpose: "Purpose", productSlug: "slot", productName: "Slot", amountMinor: 5000, currency: "NGN", refundPolicyKey: "policy", feeDisclosure: "fee", effectiveFrom: 1, effectiveTo: null, fields: [], requirements: [] }]; render(createElement(AdmissionsDashboard)); fireEvent.click(screen.getByRole("button", { name: "Copy Apply link" })); await waitFor(() => expect(clipboard).toHaveBeenCalledWith("https://apply.example.test/s/school/i/2027")); expect(screen.getByRole("link", { name: "Open Apply link" })).toHaveAttribute("href", "https://apply.example.test/s/school/i/2027"); });
  it("renders separate retention labels and confirms permanent deletion", async () => { mocks.queryResult = { mode: "never", archiveAfterDays: null, version: 1, effectiveFrom: 1 }; mocks.eligibility = { state: "archived", canArchive: false, canDelete: true, archiveBlocker: "DOCUMENT_ALREADY_ARCHIVED", deleteBlocker: null }; render(createElement(RetentionSettings)); expect(screen.getByLabelText("Never automatically archive")).toBeChecked(); expect(screen.getByLabelText("Archive delay in days")).toHaveAttribute("min", "30"); fireEvent.change(screen.getByLabelText("Document key"), { target: { value: "document-1" } }); fireEvent.click(screen.getByRole("button", { name: "Check eligibility" })); fireEvent.click(await screen.findByRole("button", { name: "Permanently delete document" })); expect(screen.getByRole("dialog")).toHaveTextContent("Permanently delete this document?"); });
  it("validates paid campaign drafts, dates, JSON definitions, and replacement-ready definitions", () => { expect(validateCampaign(valid)).toEqual([]); expect(parseDefinitions(valid)).toEqual({ fields: [], requirements: [] }); expect(validateCampaign({ ...valid, amount: "0", closesAt: valid.opensAt }).join(" ")).toMatch(/after opening|greater than zero/); expect(() => parseDefinitions({ ...valid, fieldsJson: "{}" })).toThrow(/JSON arrays/); });
  it("enforces never or integer archive minimum", () => { expect(validateRetention("never", "")).toBeNull(); expect(validateRetention("archive", "29")).toMatch(/at least 30/); expect(validateRetention("archive", "30.5")).toMatch(/integer/); expect(validateRetention("archive", "30")).toBeNull(); });
});

describe("admissions navigation and route capability gates", () => {
  it("makes admissions discoverable only with route capability and active module", () => { const allowed = access(["enrollment.applications.list"]); expect(getAccessibleWorkspaceSections("admin", { access: allowed, features: { admissions: true } }).some((item) => item.href === "/admin/admissions")).toBe(true); expect(getWorkspaceCapabilityDenial("admin", "/admin/admissions", access([]))?.state).toBe("forbidden"); expect(getWorkspaceModuleDenial("admin", "/admin/admissions", { admissions: false })?.state).toBe("module_disabled"); expect(getWorkspaceModuleDenial("admin", "/admin/admissions", {})?.state).toBe("module_disabled"); });
  it("gates queue, detail, and retention routes through the shared matrix", () => { expect(isWorkspaceBranchScopedRoute("admin", "/admin/admissions/example")).toBe(true); expect(getBranchScopedWorkspaceAccess("admin", "/admin/admissions/example", access(["enrollment.applications.view_basic"])).state).toBe("allowed"); expect(getBranchScopedWorkspaceAccess("admin", "/admin/admissions/retention", access(["enrollment.applications.view_basic"])).state).toBe("forbidden"); expect(getBranchScopedWorkspaceAccess("admin", "/admin/admissions/retention", access(["enrollment.intakes.manage"])).state).toBe("forbidden"); expect(getBranchScopedWorkspaceAccess("admin", "/admin/admissions/retention", access(["enrollment.intakes.manage", "enrollment.decisions.record"])).state).toBe("allowed"); });
});
