import { mutation, query } from "../../_generated/server";
import { ConvexError, v } from "convex/values";
import { hasSchoolCapabilityV1, resolveSchoolMembershipV1 } from "../foundation/auth";
import { audit, digest, parseDeclarativeJson } from "./helpers";

async function requireCatalogue(ctx: any, schoolId: any, capability: "admissions.catalogue.manage" | "admissions.publish" | "admissions.sensitive.configure") {
  const membership = await resolveSchoolMembershipV1(ctx, schoolId);
  if (!membership || !await hasSchoolCapabilityV1(ctx, membership, capability)) throw new ConvexError("Not found or access denied");
  return membership;
}
function slug(value: string) { const result = value.trim().toLowerCase(); if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(result)) throw new ConvexError("Invalid slug"); return result; }
function text(value: string, label: string, max = 4_000) { const result = value.trim(); if (!result || result.length > max) throw new ConvexError(`${label} is required`); return result; }
async function assertSensitiveConfiguration(ctx: any, schoolId: any, dataClass: string) { if (dataClass === "highly_sensitive" || dataClass === "financial_security") await requireCatalogue(ctx, schoolId, "admissions.sensitive.configure"); }

/** Tenant-scoped persisted catalogue projection for B3; no private application data. */
export const getCatalogue = query({
  args: { schoolId: v.id("schools") },
  returns: v.object({ programmes: v.array(v.object({ id: v.id("admissionsProgrammes"), slug: v.string(), name: v.string(), status: v.string() })), intakes: v.array(v.object({ id: v.id("admissionsIntakes"), programmeId: v.id("admissionsProgrammes"), slug: v.string(), name: v.string(), status: v.string(), opensAt: v.number(), closesAt: v.number() })), products: v.array(v.object({ id: v.id("admissionsProducts"), intakeId: v.id("admissionsIntakes"), slug: v.string(), name: v.string(), status: v.string() })), forms: v.array(v.object({ id: v.id("admissionsFormVersions"), intakeId: v.union(v.id("admissionsIntakes"), v.null()), version: v.number(), schemaVersion: v.string(), status: v.string() })) }),
  handler: async (ctx, args) => {
    await requireCatalogue(ctx, args.schoolId, "admissions.catalogue.manage");
    const programmes = await ctx.db.query("admissionsProgrammes").withIndex("by_school", (q) => q.eq("schoolId", args.schoolId)).take(100);
    const [intakes, forms] = await Promise.all([
      ctx.db.query("admissionsIntakes").withIndex("by_school", (q) => q.eq("schoolId", args.schoolId)).take(200),
      ctx.db.query("admissionsFormVersions").withIndex("by_school_and_programme", (q) => q.eq("schoolId", args.schoolId)).take(200),
    ]);
    const productLists = await Promise.all(intakes.map((intake) => ctx.db.query("admissionsProducts").withIndex("by_school_and_intake", (q) => q.eq("schoolId", args.schoolId).eq("intakeId", intake._id)).take(20)));
    const products = productLists.flat();
    return { programmes: programmes.map((item) => ({ id: item._id, slug: item.slug, name: item.name, status: item.status })), intakes: intakes.map((item) => ({ id: item._id, programmeId: item.programmeId, slug: item.slug, name: item.name, status: item.status, opensAt: item.opensAt, closesAt: item.closesAt })), products: products.map((item) => ({ id: item._id, intakeId: item.intakeId, slug: item.slug, name: item.name, status: item.status })), forms: forms.map((item) => ({ id: item._id, intakeId: item.intakeId ?? null, version: item.version, schemaVersion: item.schemaVersion, status: item.status })) };
  },
});

export const listConversionClasses = query({
  args: { schoolId: v.id("schools") },
  returns: v.array(v.object({ id: v.id("classes"), name: v.string() })),
  handler: async (ctx, args) => { await requireCatalogue(ctx, args.schoolId, "admissions.catalogue.manage"); const rows = await ctx.db.query("classes").withIndex("by_school", (q) => q.eq("schoolId", args.schoolId)).take(200); return rows.filter((row) => !row.isArchived).map((row) => ({ id: row._id, name: row.name })); },
});

export const createProgramme = mutation({
  args: { schoolId: v.id("schools"), slug: v.string(), name: v.string(), description: v.optional(v.string()) }, returns: v.id("admissionsProgrammes"),
  handler: async (ctx, args) => { const member = await requireCatalogue(ctx, args.schoolId, "admissions.catalogue.manage"); const programmeSlug = slug(args.slug); const existing = await ctx.db.query("admissionsProgrammes").withIndex("by_school_and_slug", (q) => q.eq("schoolId", args.schoolId).eq("slug", programmeSlug)).unique(); if (existing) throw new ConvexError("Programme slug already exists"); const now = Date.now(); const id = await ctx.db.insert("admissionsProgrammes", { schoolId: args.schoolId, slug: programmeSlug, name: text(args.name, "Programme name", 256), ...(args.description?.trim() ? { description: args.description.trim().slice(0, 4_000) } : {}), status: "draft", createdAt: now, updatedAt: now }); await audit({ ctx, schoolId: args.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.programme_created", entityType: "programme", entityId: String(id), outcome: "success" }); return id; },
});

export const createIntake = mutation({
  args: { schoolId: v.id("schools"), programmeId: v.id("admissionsProgrammes"), slug: v.string(), name: v.string(), cycleLabel: v.string(), opensAt: v.number(), closesAt: v.number(), targetClassId: v.optional(v.id("classes")) }, returns: v.id("admissionsIntakes"),
  handler: async (ctx, args) => { const member = await requireCatalogue(ctx, args.schoolId, "admissions.catalogue.manage"); const programme = await ctx.db.get(args.programmeId); const intakeSlug = slug(args.slug); if (!programme || programme.schoolId !== args.schoolId || !Number.isFinite(args.opensAt) || args.opensAt >= args.closesAt) throw new ConvexError("Invalid intake"); if (args.targetClassId) { const classDoc = await ctx.db.get(args.targetClassId); if (!classDoc || classDoc.schoolId !== args.schoolId) throw new ConvexError("Invalid intake"); } const duplicate = await ctx.db.query("admissionsIntakes").withIndex("by_school_and_slug", (q) => q.eq("schoolId", args.schoolId).eq("slug", intakeSlug)).unique(); if (duplicate) throw new ConvexError("Intake slug already exists"); const now = Date.now(); const id = await ctx.db.insert("admissionsIntakes", { schoolId: args.schoolId, programmeId: programme._id, slug: intakeSlug, name: text(args.name, "Intake name", 256), cycleLabel: text(args.cycleLabel, "Cycle label", 128), ...(args.targetClassId ? { targetClassId: args.targetClassId } : {}), opensAt: args.opensAt, closesAt: args.closesAt, status: "draft", createdAt: now, updatedAt: now }); await audit({ ctx, schoolId: args.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.intake_created", entityType: "intake", entityId: String(id), outcome: "success" }); return id; },
});

/** Availability changes are explicit publication actions; they never rewrite existing applications. */
export const setProgrammeStatus = mutation({
  args: { programmeId: v.id("admissionsProgrammes"), status: v.union(v.literal("published"), v.literal("closed")) }, returns: v.null(),
  handler: async (ctx, args) => { const programme = await ctx.db.get(args.programmeId); if (!programme) throw new ConvexError("Not found or access denied"); const member = await requireCatalogue(ctx, programme.schoolId, "admissions.publish"); const now = Date.now(); await ctx.db.patch(programme._id, { status: args.status, updatedAt: now }); await audit({ ctx, schoolId: programme.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.programme_status_changed", entityType: "programme", entityId: String(programme._id), outcome: "success" }); return null; },
});

export const setIntakeStatus = mutation({
  args: { intakeId: v.id("admissionsIntakes"), status: v.union(v.literal("open"), v.literal("paused"), v.literal("closed"), v.literal("archived")) }, returns: v.null(),
  handler: async (ctx, args) => { const intake = await ctx.db.get(args.intakeId); if (!intake) throw new ConvexError("Not found or access denied"); const member = await requireCatalogue(ctx, intake.schoolId, "admissions.publish"); const now = Date.now(); await ctx.db.patch(intake._id, { status: args.status, updatedAt: now }); await audit({ ctx, schoolId: intake.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.intake_status_changed", entityType: "intake", entityId: String(intake._id), outcome: "success" }); return null; },
});

export const setProductStatus = mutation({
  args: { productId: v.id("admissionsProducts"), status: v.union(v.literal("active"), v.literal("paused"), v.literal("retired")) }, returns: v.null(),
  handler: async (ctx, args) => { const product = await ctx.db.get(args.productId); if (!product) throw new ConvexError("Not found or access denied"); const member = await requireCatalogue(ctx, product.schoolId, "admissions.publish"); const now = Date.now(); await ctx.db.patch(product._id, { status: args.status, updatedAt: now }); await audit({ ctx, schoolId: product.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.product_status_changed", entityType: "product", entityId: String(product._id), outcome: "success" }); return null; },
});

export const retireForm = mutation({
  args: { formVersionId: v.id("admissionsFormVersions") }, returns: v.null(),
  handler: async (ctx, args) => { const form = await ctx.db.get(args.formVersionId); if (!form || form.status !== "published") throw new ConvexError("Form is not retireable"); const member = await requireCatalogue(ctx, form.schoolId, "admissions.publish"); const now = Date.now(); await ctx.db.patch(form._id, { status: "retired", updatedAt: now }); await audit({ ctx, schoolId: form.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.form_retired", entityType: "form", entityId: String(form._id), outcome: "success" }); return null; },
});

export const createDraftForm = mutation({
  args: { schoolId: v.id("schools"), programmeId: v.id("admissionsProgrammes"), intakeId: v.id("admissionsIntakes"), schemaVersion: v.string() }, returns: v.id("admissionsFormVersions"),
  handler: async (ctx, args) => { const member = await requireCatalogue(ctx, args.schoolId, "admissions.catalogue.manage"); const [programme, intake, versions] = await Promise.all([ctx.db.get(args.programmeId), ctx.db.get(args.intakeId), ctx.db.query("admissionsFormVersions").withIndex("by_school_and_programme", (q) => q.eq("schoolId", args.schoolId).eq("programmeId", args.programmeId)).take(100)]); if (!programme || !intake || programme.schoolId !== args.schoolId || intake.schoolId !== args.schoolId || intake.programmeId !== programme._id) throw new ConvexError("Invalid form scope"); const now = Date.now(); const id = await ctx.db.insert("admissionsFormVersions", { schoolId: args.schoolId, programmeId: programme._id, intakeId: intake._id, version: Math.max(0, ...versions.map((item) => item.version)) + 1, schemaVersion: text(args.schemaVersion, "Schema version", 128), status: "draft", createdAt: now, updatedAt: now }); await audit({ ctx, schoolId: args.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.form_drafted", entityType: "form", entityId: String(id), outcome: "success" }); return id; },
});

export const addDraftField = mutation({
  args: { formVersionId: v.id("admissionsFormVersions"), fieldKey: v.string(), sectionKey: v.string(), kind: v.string(), label: v.string(), requiredMode: v.union(v.literal("required"), v.literal("optional"), v.literal("conditional")), dataClass: v.union(v.literal("public"), v.literal("internal"), v.literal("personal"), v.literal("child_confidential"), v.literal("highly_sensitive"), v.literal("financial_security")), purpose: v.optional(v.string()), validationJson: v.string(), conditionalRuleJson: v.optional(v.string()), order: v.number() }, returns: v.id("admissionsFormFields"),
  handler: async (ctx, args) => { const form = await ctx.db.get(args.formVersionId); if (!form || form.status !== "draft") throw new ConvexError("Form is not editable"); const member = await requireCatalogue(ctx, form.schoolId, "admissions.catalogue.manage"); await assertSensitiveConfiguration(ctx, form.schoolId, args.dataClass); parseDeclarativeJson(args.validationJson, "Field validation"); if (args.requiredMode === "conditional" && !args.conditionalRuleJson) throw new ConvexError("Conditional rule is required"); if (args.conditionalRuleJson) parseDeclarativeJson(args.conditionalRuleJson, "Conditional rule"); const key = slug(args.fieldKey); const duplicate = await ctx.db.query("admissionsFormFields").withIndex("by_form_version_and_field_key", (q) => q.eq("formVersionId", form._id).eq("fieldKey", key)).unique(); if (duplicate || !Number.isInteger(args.order) || args.order < 0) throw new ConvexError("Invalid field"); const now = Date.now(); const id = await ctx.db.insert("admissionsFormFields", { schoolId: form.schoolId, formVersionId: form._id, fieldKey: key, sectionKey: text(args.sectionKey, "Section", 128), kind: text(args.kind, "Field kind", 64), label: text(args.label, "Field label", 256), requiredMode: args.requiredMode, dataClass: args.dataClass, ...(args.purpose?.trim() ? { purpose: args.purpose.trim().slice(0, 1_000) } : {}), validationJson: args.validationJson, ...(args.conditionalRuleJson ? { conditionalRuleJson: args.conditionalRuleJson } : {}), order: args.order, status: "active", createdAt: now, updatedAt: now }); await audit({ ctx, schoolId: form.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.field_added", entityType: "form_field", entityId: String(id), outcome: "success" }); return id; },
});

export const addDraftDocumentRequirement = mutation({
  args: { formVersionId: v.id("admissionsFormVersions"), requirementKey: v.string(), category: v.string(), label: v.string(), requiredMode: v.union(v.literal("required"), v.literal("optional"), v.literal("conditional")), acceptedMimeTypes: v.array(v.string()), maxBytes: v.number(), maxFiles: v.number(), sensitivity: v.union(v.literal("public"), v.literal("internal"), v.literal("personal"), v.literal("child_confidential"), v.literal("highly_sensitive"), v.literal("financial_security")), purpose: v.string(), conditionJson: v.optional(v.string()), order: v.number() }, returns: v.id("admissionsDocumentRequirements"),
  handler: async (ctx, args) => { const form = await ctx.db.get(args.formVersionId); if (!form || form.status !== "draft") throw new ConvexError("Form is not editable"); const member = await requireCatalogue(ctx, form.schoolId, "admissions.catalogue.manage"); await assertSensitiveConfiguration(ctx, form.schoolId, args.sensitivity); const key = slug(args.requirementKey); if (!Number.isInteger(args.maxBytes) || args.maxBytes < 1 || args.maxBytes > 50_000_000 || !Number.isInteger(args.maxFiles) || args.maxFiles < 1 || args.maxFiles > 10 || args.acceptedMimeTypes.length < 1 || args.acceptedMimeTypes.length > 20 || args.acceptedMimeTypes.some((mime) => !/^[\w.+-]+\/[\w.+-]+$/.test(mime)) || (args.requiredMode === "conditional" && !args.conditionJson)) throw new ConvexError("Invalid document requirement"); if (args.conditionJson) parseDeclarativeJson(args.conditionJson, "Conditional rule"); const duplicate = await ctx.db.query("admissionsDocumentRequirements").withIndex("by_form_version_and_requirement_key", (q) => q.eq("formVersionId", form._id).eq("requirementKey", key)).unique(); if (duplicate) throw new ConvexError("Requirement key already exists"); const now = Date.now(); const id = await ctx.db.insert("admissionsDocumentRequirements", { schoolId: form.schoolId, formVersionId: form._id, requirementKey: key, category: text(args.category, "Document category", 128), label: text(args.label, "Document label", 256), requiredMode: args.requiredMode, acceptedMimeTypes: args.acceptedMimeTypes, maxBytes: args.maxBytes, maxFiles: args.maxFiles, sensitivity: args.sensitivity, purpose: text(args.purpose, "Document purpose", 1_000), ...(args.conditionJson ? { conditionJson: args.conditionJson } : {}), order: args.order, createdAt: now, updatedAt: now }); await audit({ ctx, schoolId: form.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.document_requirement_added", entityType: "document_requirement", entityId: String(id), outcome: "success" }); return id; },
});

/** Publishing is one-way: draft rows become immutable and an intake can expose exactly one published form. */
export const publishForm = mutation({
  args: { formVersionId: v.id("admissionsFormVersions") }, returns: v.null(),
  handler: async (ctx, args) => { const form = await ctx.db.get(args.formVersionId); if (!form || form.status !== "draft" || !form.intakeId) throw new ConvexError("Form is not publishable"); const member = await requireCatalogue(ctx, form.schoolId, "admissions.publish"); const fields = await ctx.db.query("admissionsFormFields").withIndex("by_form_version_and_order", (q) => q.eq("formVersionId", form._id)).take(200); if (fields.some((field) => (field.dataClass === "highly_sensitive" || field.dataClass === "financial_security") && !field.purpose)) throw new ConvexError("Sensitive field requires purpose"); const existing = await ctx.db.query("admissionsFormVersions").withIndex("by_intake_and_status", (q) => q.eq("intakeId", form.intakeId!).eq("status", "published")).take(2); if (existing.length) throw new ConvexError("Retire the current published form before publishing"); const now = Date.now(); await ctx.db.patch(form._id, { status: "published", publishedAt: now, publishedBy: member.userId, updatedAt: now }); await audit({ ctx, schoolId: form.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.form_published", entityType: "form", entityId: String(form._id), outcome: "success" }); return null; },
});

export const createDeclaration = mutation({
  args: { schoolId: v.id("schools"), programmeId: v.id("admissionsProgrammes"), version: v.number(), title: v.string(), body: v.string(), purpose: v.string() }, returns: v.id("admissionsDeclarationVersions"),
  handler: async (ctx, args) => { const member = await requireCatalogue(ctx, args.schoolId, "admissions.publish"); const programme = await ctx.db.get(args.programmeId); if (!programme || programme.schoolId !== args.schoolId || !Number.isInteger(args.version) || args.version < 1) throw new ConvexError("Invalid declaration"); const existing = await ctx.db.query("admissionsDeclarationVersions").withIndex("by_school_and_programme_and_version", (q) => q.eq("schoolId", args.schoolId).eq("programmeId", programme._id).eq("version", args.version)).unique(); if (existing) throw new ConvexError("Declaration version exists"); const now = Date.now(); const body = text(args.body, "Declaration body", 20_000); const id = await ctx.db.insert("admissionsDeclarationVersions", { schoolId: args.schoolId, programmeId: programme._id, version: args.version, title: text(args.title, "Declaration title", 256), body, bodyDigest: await digest(body), purpose: text(args.purpose, "Declaration purpose", 1_000), status: "published", publishedAt: now, publishedBy: member.userId, createdAt: now, updatedAt: now }); return id; },
});


export const createProduct = mutation({
  args: { schoolId: v.id("schools"), intakeId: v.id("admissionsIntakes"), slug: v.string(), name: v.string() }, returns: v.id("admissionsProducts"),
  handler: async (ctx, args) => { const member = await requireCatalogue(ctx, args.schoolId, "admissions.catalogue.manage"); const intake = await ctx.db.get(args.intakeId); const productSlug = slug(args.slug); if (!intake || intake.schoolId !== args.schoolId) throw new ConvexError("Invalid product"); const duplicate = await ctx.db.query("admissionsProducts").withIndex("by_school_and_slug", (q) => q.eq("schoolId", args.schoolId).eq("slug", productSlug)).unique(); if (duplicate) throw new ConvexError("Product slug already exists"); const now = Date.now(); const id = await ctx.db.insert("admissionsProducts", { schoolId: args.schoolId, intakeId: intake._id, slug: productSlug, name: text(args.name, "Product name", 256), slotCount: 1, status: "draft", createdAt: now, updatedAt: now }); await audit({ ctx, schoolId: args.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.product_created", entityType: "product", entityId: String(id), outcome: "success" }); return id; },
});

export const publishPrice = mutation({
  args: { productId: v.id("admissionsProducts"), version: v.number(), amountMinor: v.number(), currency: v.string(), refundPolicyKey: v.string(), feeDisclosure: v.string(), effectiveFrom: v.number(), effectiveTo: v.optional(v.number()) }, returns: v.id("admissionsProductPrices"),
  handler: async (ctx, args) => { const product = await ctx.db.get(args.productId); if (!product || !Number.isInteger(args.version) || args.version < 1 || !Number.isInteger(args.amountMinor) || args.amountMinor < 0 || !Number.isFinite(args.effectiveFrom) || (args.effectiveTo !== undefined && args.effectiveTo <= args.effectiveFrom)) throw new ConvexError("Invalid price"); const member = await requireCatalogue(ctx, product.schoolId, "admissions.publish"); const existing = await ctx.db.query("admissionsProductPrices").withIndex("by_product_and_version", (q) => q.eq("productId", product._id).eq("version", args.version)).unique(); if (existing) throw new ConvexError("Price version exists"); const now = Date.now(); const id = await ctx.db.insert("admissionsProductPrices", { schoolId: product.schoolId, productId: product._id, version: args.version, amountMinor: args.amountMinor, currency: text(args.currency, "Currency", 8).toUpperCase(), refundPolicyKey: text(args.refundPolicyKey, "Refund policy", 128), feeDisclosure: text(args.feeDisclosure, "Fee disclosure", 4_000), effectiveFrom: args.effectiveFrom, ...(args.effectiveTo !== undefined ? { effectiveTo: args.effectiveTo } : {}), status: "published", createdAt: now, updatedAt: now }); await audit({ ctx, schoolId: product.schoolId, actor: { kind: "staff", userId: member.userId }, action: "catalogue.price_published", entityType: "product_price", entityId: String(id), outcome: "success" }); return id; },
});
